- name: Install Postgres
  hosts: dbserver
  become: yes
  gather_facts: false
  vars:
    dbname: test_db
    dbuser: postgres
    dbpassword: postgres
  tasks:
  - name: apt cache update
    apt: update_cache=yes
  - name: packages installation
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  ##- name: ensure user does not have unnecessary privilege
  ##  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  
  - name: ensure no other user can access the database
    postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent