- name: Install App
  hosts: service
  remote_user: ubuntu
  tasks:
    - name: Update the Ubuntu system and services
      apt: update_cache=yes
      become: yes
      become_method: sudo
    - name: Install Basic Unix-level Services
      apt: name={{ item }} state=latest
      become: yes
      become_method: sudo
      with_items:
        - python3
        - python3-pip
        - git
    - name: add github ssh key
      copy: >
        src=/files/id_rsa.github
        dest=/root/.ssh/id_rsa.github
        owner=root
        group=root
        mode=0600
    - name: create directory if not exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      with_items:
        - /myapp
    - name: clone git repo
      git:
        repo: git@github.com:repo.git
        dest: /myapp/
        version: master
        accept_hostkey: yes
        key_file: root/.ssh/id_rsa.github
      become_user: root
    - name: Install app dependencies
      shell: cd "/myapp/" && pip3 install -r requirements.txt && nohup python3 main.py &
    - name: Validating the port is open
      tags: nodevalidate
      wait_for:
        host: "localhost"
        port: 8080
        delay: 10
        timeout: 30
        state: started
        msg: "App is not running"